# Preface {-}

## Introducción {-}

Este es el Notebook de los directos en Twitch del tito S4vitar. Aqui podreis encontrar los passos importantes de cada maquina
echa. Este book no tiene que estar considerado como una lista de Walktrough, pero mas como unas notas de tecnicas utilizadas
durante la resolucion de maquinas. Por cierto no estara listado las contraseñas o algunos usuarios, menos si estan utilizados en los
comandos.

Cada maquina esta separada de la manera siguiente:

- Introduccion y link del directo
- Fase de enumeracion
- Notas sobre las vulnerabilidades econtradas
- Explotacion de vulnerabilidades para ganar accesso a la maquina victima
- Parte de escalacion de privilegios

Espero que este book ayude a la comunidad. 

Todas las notas estan disponibles separadas por tipos y categorias en el [hacking Notebook](https://looping404.michellopez.org).

## Agradecimietos {-}

Me gustaria dar las gracias a S4vitar por su contenido de calidad y las ganas que mete a lo que hace para la comunidad.
Son estas ganas que me motivaron en querer aprender mas y mas. Y como la mejor manera que tengo de aprender es tomando notas,
este book no existiria sin el.
